### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [4, 40962, 3] at entry 0 and [4, 36685, 3] at entry 1

### ISSUE THREAD

**Issue by WilliamAshbee** [ai-med/Vox2Cortex#4]
I ran preprocessing on this dataset, but still get this error. 
[INFO] Created training loader of length 5
Traceback (most recent call last):
  File "main.py", line 260, in <module>
    main(hyper_ps)
  File "main.py", line 256, in main
    loglevel=hps['LOGLEVEL'], resume=args.resume)
  File "/v2c/vox2cortex/utils/train.py", line 556, in training_routine
    start_epoch=start_epoch)
  File "/v2c/vox2cortex/utils/train.py", line 322, in train
    for iter_in_epoch, data in enumerate(training_loader):
  File "/opt/miniconda3/envs/vox2cortex/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/opt/miniconda3/envs/vox2cortex/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/miniconda3/envs/vox2cortex/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/opt/miniconda3/envs/vox2cortex/lib/python3.7/site-packages/torch/utils/
data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/miniconda3/envs/vox2cortex/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/miniconda3/envs/vox2cortex/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [4, 40962, 3] at entry 0 and [4, 36685, 3] at entry 1

**Comment by fabibo3** [comment]
Looks like the target surfaces do not all have the same number of target points. You could try setting the parameter N_REF_POINTS_PER_STRUCTURE (default value 40962) to the minimum number of vertices in your dataset, which is probably <=36685.

**Comment by WilliamAshbee** [comment]
Hmm, I'm still having problems with this. I'm guessing based on your feedback you worked with a more homogenous dataset. I'm guessing this might get dirty. (I spent some months working on some other projects), this is basically the final project I need to work on. I need to get this working somehow. :)

**Comment by fabibo3** [comment]
hm, have you tried with batch size 1?

**Comment by WilliamAshbee** [comment]
doesn't seem to fix the problem. still beating my head against this.

**Comment by WilliamAshbee** [comment]
There is some discussion in the code about padding ( i assume that  padding is used to accommodate variable sizes )

**Comment by WilliamAshbee** [comment]
Ok, batch size equal to 1 fixes it, but apparently I have to set the batch size equal to 1 in the train.py file because it was ignoring it when I set it in some of the other places. Probably I have a poor understanding of the config structure of the project. I'm going to close this, but it would be an ideal thing to fix this. Maybe if i work with this codebase long term i will fix this.

**Comment by WilliamAshbee** [comment]
**From other thread for others:** 
```
The batch size was limited by GPU memory in our experiments, we used batch size 1 for OASIS and batch size 2 for ADNI experiments.

The FreeSurfer surfaces can have different numbers of vertices, just make sure you set the parameter 'N_REF_POINTS_PER_STRUCTURE' to the min. number of vertices in your training set (per surface). See also https://github.com/ai-med/Vox2Cortex/issues/4.
```
